name: Tests automatiques
run-name: ${{ github.actor }} lance les tests du projet (front)
on: [pull_request]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --openssl-legacy-provider
      
    steps:
      - run: echo "Action lancée par l'evenement ${{ github.event_name }} sur la branche ${{ github.ref }} de ${{ github.repository }}."
      
      - name: Checkout
        uses: actions/checkout@v6
        
      - run: echo "Checkout de ce repo."
      
      - name: Liste des fichiers
        run: ls ${{ github.workspace }}
          
      - name: Configurer Node.js 18
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Lancement des tests
        run: |
          cd front
          npm install
          # 2. On injecte de force la variable dans le shell juste avant l'exécution
          export NODE_OPTIONS=--openssl-legacy-provider
          npm test -- --watch=false --browsers=ChromeHeadless
          
      - run: echo "Statut de l'action --> ${{ job.status }}."
